language: ruby
cache: bundler

rvm:
  - 2.1.0
  - 2.1.2

script: 'bundle exec rspec spec'

notifications:
  email:
    recipients:
      - dean@shopkeep.com
    on_failure: change
    on_success: never
