language: ruby
cache: bundler

rvm:
  - 2.1.2

branches:
  only:
    - master

script: 'bundle exec rake'

notifications:
  email:
    recipients:
      - dean@shopkeep.com
    on_failure: change
    on_success: never
